WIP Fixing mTLS via Spire after refactor
greymatter-io/operator pull request #101
Opened 2022-04-14 21:56 UTC by danielpcox

[sc-11585]

2022-04-18 22:19 UTC, danielpcox commented
Assuming CI succeeds, this one is good to go. Sorry for combining a directory restructure with substantial code changes... In any case, you can confirm it deploys into a fresh reset of Rancher Desktop with the instructions in the Quick Install section.

2022-04-19 14:27 UTC, bcmendoza commented
@danielpcox could you run `go mod tidy && go mod vendor`? The current module files on your branch still have `evanphx/json-ptach`, `ghodss/yaml`, and `k8s.io/component-base`.

2022-04-19 14:48 UTC, dontlaugh commented
@jack-bischoff can you install Rancher and try this?

2022-04-19 18:36 UTC, dontlaugh requested changes
Let's make the k8s stuff we're checking in a separate PR; it'll make this easier to review.

2022-04-19 19:32 UTC, jack-bischoff commented
On rancher Version: 1.2.1.
Running the install steps on the branch readme, the operator pod successfully installed:
```
➜ k --kubeconfig ~/.kube/config get po -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS      AGE
kube-system   helm-install-traefik-crd--1-xsg89         0/1     Completed   0             4h1m
kube-system   helm-install-traefik--1-qlrhf             0/1     Completed   1             4h1m
kube-system   svclb-traefik-tkzl2                       2/2     Running     2 (17m ago)   4h1m
kube-system   local-path-provisioner-84bb864455-jd46n   1/1     Running     1 (17m ago)   4h1m
kube-system   coredns-96cc4f57d-4n7zw                   1/1     Running     1 (17m ago)   4h1m
kube-system   traefik-56c4b88c4b-7tsvt                  1/1     Running     1 (17m ago)   4h1m
kube-system   metrics-server-ff9dbcb6c-jxzfn            1/1     Running     1 (17m ago)   4h1m
gm-operator   gm-operator-0                             1/1     Running     0             6m25s
spire         server-0                                  2/2     Running     0             6m24s
spire         agent-868f4                               1/1     Running     0             6m24s
```

The operator, however, did not automatically apply the Mesh CR, according to this line in the readme: 
> The operator will be running in a pod in the gm-operator namespace, and shortly after installation, the default Mesh CR described in pkg/cuemodule/inputs.cue will be automatically deployed.

Investigating the logs show that an error occured:
```
{"level":"error","ts":1650395895.8050022,"logger":"k8sapi","msg":"create","Mesh":{"name":"mymesh"},"error":"Internal error occurred: failed calling webhook \"mutate-mesh.greymatter.io\": failed to call webhook: Post \"https://gm-webhook.gm-operator.svc:443/mutate-mesh?timeout=10s\": dial tcp 10.43.139.204:443: connect: connection refused"}
```

That may explain why the operator failed to fully launch. But I do not know if that is related to the work in this PR or a local configuration problem

2022-04-19 19:57 UTC, bcmendoza requested changes

2022-04-19 19:57 UTC, bcmendoza commented on pkg/cuemodule/gm/outputs/catalogentries.cue
> +		service_id: "catalog" // Catalog lives behind the controlensemble sidecar, for the moment
remove docstring

2022-04-19 20:02 UTC, jack-bischoff requested changes

2022-04-20 16:17 UTC, danielpcox commented
> Let's make the k8s stuff we're checking in a separate PR; it'll make this easier to review.

@dontlaugh I just did this and pushed. For everyone else's information: The build will break, but the PR will be more navigable for review.

2022-04-20 16:19 UTC, danielpcox commented on CHANGELOG.md
> +- Opt-in flag that causes the operator to automatically deploy the default mesh defined in the CUE,
No. It's opt-in, meaning the default is _not_ to do it, and you have to opt-in if you want it. You have to set it to true, that is. Ironically, it's set to true right now in the CUE. I always intended to set it to false before the PR, but now I'm not so sure, and I don't think it matters very much for the purposes of this PR.

2022-04-20 16:20 UTC, danielpcox commented on README.md
>  ```bash
Good catch. I intended to make it into one block, but I missed a spot. I'll fix it.

2022-04-20 16:22 UTC, danielpcox commented on main.go
> +		LeaderElectionID:        "715805a0.greymatter.io", // TODO shouldn't this be generated?
I'm just confused about why there would be an obscure random-looking ID hard-coded in there. If it's hard-coded, why not make it human-readable? More likely I thought it should be generated, since later we're going to support deploying multiple operators, and they're probably going to need different IDs, right?

2022-04-20 16:24 UTC, danielpcox commented on pkg/cuemodule/cue.mod/gen/github.com/greymatter-io/operator/api/v1alpha1/mesh_options_go_gen.cue
> +#UserToken: {
I'm not sure I understand. I didn't intentionally create this file, so I imagine it will reappear when we later re-run the generation?

2022-04-20 16:25 UTC, danielpcox commented on pkg/cuemodule/cue.mod/gen/github.com/greymatter-io/operator/api/v1alpha1/mesh_types_go_gen.cue
> +	release_version: string @go(ReleaseVersion)
Let's do that in a separate PR? I'd prefer to do it as part of a more general sweep over the Mesh CRD to revisit what we do and don't need.

2022-04-20 16:28 UTC, danielpcox commented on pkg/cuemodule/gm/intermediates.cue
> +      forward_client_cert_details: "APPEND_FORWARD"
So does that mean we don't need to put these in? Sounds like you don't know what they're for either? Anyway, I'm going to leave that comment in for now until it makes sense to me, or we go 1.0, 'cause there's a chance we don't need those keys.

2022-04-20 16:31 UTC, danielpcox commented on pkg/cuemodule/gm/outputs/catalogentries.cue
> +		service_id: "catalog" // Catalog lives behind the controlensemble sidecar, for the moment
I don't understand this comment. What docstring? Are you saying I should remove some docstring, or just pointing out that I did remove some docstring?

2022-04-20 16:34 UTC, danielpcox commented on pkg/cuemodule/inputs.cue
> +  spire: bool | *true // enable Spire-based mTLS DEBUG - the default should be false
Yes, at least eventually. :) Whether it should for this PR or not is unclear to me, and I'm inclined to leave it. I'd like to get the CI build to launch multiple versions of the mesh with different flag settings to test them all, and I think that's the point at which I'll feel comfortable putting the flags into reasonable defaults. For now, I'd say leave this set to true so that the build tests the spire setup by default (which is more complicated and therefore more likely to break)

2022-04-20 16:34 UTC, danielpcox commented on pkg/cuemodule/inputs.cue
> +  auto_apply_mesh: bool | *true // apply the default mesh specified above after a delay // TODO, not actually used yet - implement
Yes! I'll take off the TODO

2022-04-20 16:39 UTC, danielpcox commented on pkg/cuemodule/inputs.cue
> +    release_version: string | *"1.7" // no longer does anything, for the moment
Discussion here: https://github.com/greymatter-io/operator/pull/101/files#r853216948

2022-04-20 16:42 UTC, danielpcox commented on pkg/cuemodule/inputs.cue
> +  redis_spire_subjects: [...string] | *["dashboard", "catalog", "controlensemble", "edge"]
I actually had exactly that^ in there, and then took it out. I'm still torn about it. Maybe you're right, but I think the formulation as it is makes things easier for a new user of the CUE to figure out what's going on. That said, it's still confusing, and I'd love to revisit this later.

2022-04-20 16:43 UTC, danielpcox commented on pkg/cuemodule/inputs.cue
> +      operator: string | *"docker.greymatter.io/internal/gm-operator:local_refactored"
Good point. Will do.

2022-04-20 16:44 UTC, dontlaugh commented
> > Let's make the k8s stuff we're checking in a separate PR; it'll make this easier to review.
> 
> @dontlaugh I just did this and pushed. For everyone else's information: The build will break, but the PR will be more navigable for review.

Okay cool. I will come review this again after the k8s PR is merged, and this PR is rebased.

Make sure the K8s PR is the one with a changelog entry about checking in those files. We will want that `git blame` to point back to the commit where the generated files were introduced.

2022-04-20 17:01 UTC, danielpcox commented
@dontlaugh OK, https://github.com/greymatter-io/operator/pull/102 created, and this PR has been rebased onto it.

2022-04-20 21:11 UTC, bcmendoza commented on pkg/cuemodule/gm/outputs/catalogentries.cue
> +		service_id: "catalog" // Catalog lives behind the controlensemble sidecar, for the moment
Oh, I was requesting a removal of the docstring/comment since Catalog no longer lives behind controlensemble

2022-04-20 21:14 UTC, bcmendoza commented on pkg/cuemodule/gm/intermediates.cue
> +      forward_client_cert_details: "APPEND_FORWARD"
Nope, I was just answering why these two values are in here for context. I also do not know what they do :)

2022-04-20 21:14 UTC, dontlaugh commented on CHANGELOG.md
> +- Opt-in flag that causes the operator to automatically deploy the default mesh defined in the CUE,
What's the actual flag? Let's mention it specifically here.

2022-04-20 21:18 UTC, bcmendoza commented on main.go
> +		LeaderElectionID:        "715805a0.greymatter.io", // TODO shouldn't this be generated?
Yes, it makes sense that we will need unique IDs per operator cluster. The reason for the weird ID is that it was generated by operator-sdk when this project was first scaffolded.

2022-04-20 21:19 UTC, dontlaugh commented on pkg/cuemodule/cue.mod/gen/github.com/greymatter-io/operator/api/v1alpha1/mesh_types_go_gen.cue
> +	release_version: string @go(ReleaseVersion)
Leave it for now. As for the Makefile, I want it deconstructed completely into the parts we really need, and get rid of the stuff we don't.

2022-04-20 21:20 UTC, dontlaugh commented on pkg/cuemodule/gm/intermediates.cue
> +      forward_client_cert_details: "APPEND_FORWARD"
@alecholmez any thoughts here?

2022-04-20 21:20 UTC, bcmendoza commented on CHANGELOG.md
> +- Opt-in flag that causes the operator to automatically deploy the default mesh defined in the CUE,
Hah… it being set to true right now is why I proposed calling it opt-out. I thought an automatic mesh was supposed to be the default behavior.

2022-04-20 21:21 UTC, dontlaugh commented on pkg/cuemodule/gm/outputs/EXTRACTME.cue
> +// for CLI convenience
Which CLI? Is there an example command we can put in a comment here?

2022-04-20 21:23 UTC, dontlaugh commented on pkg/cuemodule/load.go
> +type Config struct {
Add Go docstrings to these exported structs and methods.

2022-04-20 21:23 UTC, bcmendoza commented on pkg/cuemodule/cue.mod/gen/github.com/greymatter-io/operator/api/v1alpha1/mesh_options_go_gen.cue
> +#UserToken: {
I don’t think so. My assumption is that when Alec merged these in, he still had this file from a previous generation. mesh_options.go does not exist anymore, so this file won’t get generated.

2022-04-20 21:42 UTC, dontlaugh requested changes
I don't have any big changes. Just some comments on style and a few points of clarification. I'm inclined to merge after that.

What's the story around CI? We can merge this "red", but if that's the case we need an immediate follow up that makes it green and verifies that greymatter is at least running.

2022-04-20 21:42 UTC, dontlaugh commented on pkg/gmapi/cli.go
> +	SidecarList []string
Does this struct member need to be public?

2022-04-20 21:42 UTC, dontlaugh commented on pkg/mesh_install/installer.go
>  	}, nil
Just a comment: Using struct literal syntax, combined with Go's fmt, makes diffs noiser than they should be. Note that not every field in this struct changed, but we get a diff on all of it.

Prefer this:

```go
var t Thing
t.field1 = "okay"
t.field2 = "fine"
t.field3 = "coleman"
return &t
```

2022-04-20 21:42 UTC, dontlaugh commented on pkg/mesh_install/installer.go
> +	// TODO the operator itself can launch _all_ the Spire manifests, as before, after a check that they aren't already there.
Clarify this "TODO"

2022-04-20 21:42 UTC, dontlaugh commented on pkg/mesh_install/installer.go
> +func injectPKI(secret *corev1.Secret, cs *cfsslsrv.CFSSLServer) (*corev1.Secret, error) {
Let's change this name to something more specific like injectIntermediateCA or something along those lines.

2022-04-20 21:49 UTC, danielpcox commented on pkg/cuemodule/gm/outputs/EXTRACTME.cue
> +// for CLI convenience
I'll put an example of the CUE that uses one of these.

2022-04-20 22:13 UTC, danielpcox commented on pkg/gmapi/cli.go
> +	SidecarList []string
At the moment, yes, because I load initial data into it from outside, here: https://github.com/greymatter-io/operator/blob/fixing_spire_after_refactor/pkg/mesh_install/installer.go#L63

2022-04-20 22:16 UTC, danielpcox commented on pkg/mesh_install/installer.go
>  	}, nil
Personally, I prefer the struct literal syntax with a _small_ bit of extra noise in the diff, because it's more readable as you're reading the code.

2022-04-20 22:17 UTC, danielpcox commented on pkg/mesh_install/installer.go
> +	// TODO the operator itself can launch _all_ the Spire manifests, as before, after a check that they aren't already there.
This TODO is obsolete, so I removed it.

2022-04-20 22:17 UTC, danielpcox commented on pkg/mesh_install/installer.go
> +func injectPKI(secret *corev1.Secret, cs *cfsslsrv.CFSSLServer) (*corev1.Secret, error) {
I'll do that. I pulled this one remaining function in from spire.go and then deleted spire.go, without changing its name.

2022-04-20 22:25 UTC, danielpcox commented on pkg/cuemodule/gm/outputs/catalogentries.cue
> +		service_id: "catalog" // Catalog lives behind the controlensemble sidecar, for the moment
Oh, good point. I'll fix that.

2022-04-20 22:26 UTC, danielpcox commented on main.go
> +		LeaderElectionID:        "715805a0.greymatter.io", // TODO shouldn't this be generated?
Ah, that makes sense. OK, we'll revisit this when we do multi-operator stuff in a future PR.

2022-04-20 22:27 UTC, dontlaugh commented on pkg/cuemodule/gm/intermediates.cue
> +      forward_client_cert_details: "APPEND_FORWARD"
No blockers from me, fwiw.

2022-04-20 22:29 UTC, danielpcox commented on CHANGELOG.md
> +- Opt-in flag that causes the operator to automatically deploy the default mesh defined in the CUE,
I've mentioned the flag by name and removed the apparently confusing comment that it's "opt-in" entirely. Just "Added a flag (`auto_apply_mesh`)..."

2022-04-20 22:33 UTC, danielpcox commented on pkg/cuemodule/cue.mod/gen/github.com/greymatter-io/operator/api/v1alpha1/mesh_options_go_gen.cue
> +#UserToken: {
OK, I'll remove it.

2022-04-20 22:58 UTC, dontlaugh requested changes
No blockers from me. Let's make the integration tests go a bit deeper in the follow up PR.

2022-04-21 14:43 UTC, jack-bischoff approved these changes

2022-04-21 14:53 UTC, merged