WIP Operator graceful restart
greymatter-io/operator pull request #106
Opened 2022-04-27 22:43 UTC by danielpcox

Solves [sc-13114] by reloading a deployed Mesh CR if there is one to restore its state, and not auto-applying a mesh if this has happened.

Also incidentally completed [sc-13231] by reloading the OperatorCUE before attempting to unify it with the updated mesh. This avoids a conflict between the concrete values of the old and new versions of the Mesh.

2022-04-27 22:44 UTC, danielpcox commented
Left to do is reloading the SidecarList for populating Spire subjects.

1. Store the SidecarList in the Mesh whenever it changes
2. Reload it when we reload the Mesh on restart

2022-04-28 15:13 UTC, dontlaugh commented on pkg/mesh_install/installer.go
> +			i.OperatorCUE.UnifyWithMesh(i.Mesh)
This method should return an error

2022-05-03 19:33 UTC, danielpcox commented
This is ready for review. I've tested it myself by restarting the operator and confirming the values were correctly loaded, as well as deploying/undeploying a workload to confirm that sidecar injection functions correctly both before and after an operator restart.

To test it yourself, follow the Quick Install steps to launch the operator, and notice that restarting the operator restores it to the same state it was in before the restart, eventually.

2022-05-03 20:36 UTC, dontlaugh requested changes
Update the CHANGELOG

2022-05-03 20:50 UTC, dontlaugh approved these changes
If this passes test, merge it

2022-05-03 21:13 UTC, merged