Optimize and expand integration tests
greymatter-io/operator pull request #107
Opened 2022-04-28 23:55 UTC by jack-bischoff

Please see https://buildkite.com/greymatter/operator/builds/554 for the status of the tests.

This pr adds a few features. 
First, the wait times for async actions, like
installing the operator, are minimized by replacing estimated sleeps with
polling. Particularly, the wait_for_resource and curl_retry use polling with a
few second delay to effectively wait for pods and other resources to become
available and for servers to begin accepting requests, respectively.

Second, the pr adds stricter and more test assertions. These include actions like
testing for existence (and lack thereof) of pods, testing network
accessibility, and testing for readiness by a timeout (failing to be ready by a
timeout likely indicates an error as the timeouts are generous). 

Lastly, the pr expands the testing profile and facilitates future expansions by generating n pipelines and creating n k3s
clusters, where n is the number of operator tests or configurations which need
a clean machine. It does so by tagging the ec2 with the test name and including
that tag in the pipeline; an extension of the same pattern used to generate and
link just the one ec2.

There are currently three separate integration tests: one is a default installation, the other is a no spire installation, and the last creates and deletes mesh CRs to if creating meshes deploy the gm services properly and if deleting them destroys services properly.

Note, one test assertion was disabled for the tear down scenario due to a bug that Daniel may be working on. Once that fix gets merged in, then that test can be re-enabled.

2022-04-29 17:07 UTC, dontlaugh commented on .buildkite/pipeline.yaml
>        - ./scripts/cibuild release
Note that we are still uploading containers to nexus right here, regardless of the outcome of integration tests. 

Not a blocker for this PR, but change this soon.

2022-04-29 17:08 UTC, dontlaugh commented on scripts/cibuild
> +
remove this newline

2022-04-29 17:10 UTC, dontlaugh commented on scripts/cibuild
> +    steps_yaml+=("""
An alternative to accumulating in an array here would be echoing to a tmp file.

2022-04-29 17:12 UTC, dontlaugh commented on scripts/test
> +    if [ $timeout -eq 0 ]; then
would `-lt` be better? if someone changes numbers to a non-multiple of 5 this might break?

2022-04-29 17:13 UTC, dontlaugh commented on scripts/test
> +# A helper function     Installs the operator with provided tags
Rewrite this comment to refer to the cue used

2022-04-29 17:13 UTC, dontlaugh commented on scripts/test
> +  tags=$1
...where possible. :)

2022-04-29 17:17 UTC, dontlaugh requested changes
This is looking fine; The bashisms are complex but ths is a reasonable approach.

Because they're complex, zoom out a little and write a longer comment above each test case that describes the routine.

2022-04-29 17:34 UTC, jack-bischoff commented on scripts/test
> +    if [ $timeout -eq 0 ]; then
Ah yes great catch

2022-04-29 17:58 UTC, dontlaugh commented on scripts/cibuild
> +    steps_yaml+=("""
Not necessarily, but just keep it in mind next time, since it might be easier during the development phase.

2022-04-29 21:44 UTC, danielpcox approved these changes
This looks great to me. I love that you're actually checking for connectivity and got rid of the waits, and I love multiple parallel environments for different configurations.

One nit: Could you rewrite it all in Python?

Oh, and `_wait_for_resouce` is misspelled.

2022-05-02 17:22 UTC, dontlaugh approved these changes

2022-05-02 17:31 UTC, merged