Build operator installation manifests
greymatter-io/operator pull request #112
Opened 2022-05-09 21:28 UTC by danielpcox

Per [the plan described here](https://app.shortcut.com/grey-matter/story/13238/publish-operator-installation-manifests-to-our-website-curl-bash-script#activity-14086), build manifests to install the operator with certain flags already set.

These are intended to be published somewhere so that operator installation becomes simply a matter of applying them, e.g. with `kubectl apply -f https://greymatter.io/operator/v1.0_withspire.yaml` (followed immediately by creation of `gm-docker-secret` in the `gm-operator` namespace).

2022-05-10 22:46 UTC, dontlaugh reviewed
Can we invoke this manifest generation in CI? We can use `buildkite-agent upload` to save a version of these in buildkite's temporary storage.

2022-05-11 14:56 UTC, dontlaugh requested changes
Have CI build this and then upload the artifacts.

2022-05-11 16:31 UTC, danielpcox commented
Yay

![image](https://user-images.githubusercontent.com/56411/167900986-f90326a5-b93a-4faf-a885-9b75c521df61.png)

2022-05-11 17:22 UTC, dontlaugh approved these changes
LGTM :+1:  Squash this down and make the commit nice.

2022-05-12 14:45 UTC, merged