WIP OpenShift support
greymatter-io/operator pull request #116
Opened 2022-05-20 21:44 UTC by danielpcox

[sc-14680]

Restoring basic (non-GUI) OpenShift support to the operator.

2022-05-25 21:34 UTC, dontlaugh commented on scripts/cibuild
> +  cases=('default' 'with_spire' 'tear_down')
Can we maintain both variants?

2022-05-25 21:37 UTC, dontlaugh commented on pkg/cuemodule/load.go
> +			logger.Error(fmt.Errorf("got unrecognized K8s manifest object from CUE"), "ignoring", "Kind", ke.Kind, "Object", manifest)
if you don't need a formatting string, prefer `errors.New`

2022-05-25 21:39 UTC, dontlaugh reviewed
Looks good. 

IMO, you can be more aggressive with docstrings in the CUE. Where things come from, how they fit together, etc.

2022-05-26 14:44 UTC, danielpcox commented on scripts/cibuild
> +  cases=('default' 'with_spire' 'tear_down')
Technically, 'default' is the other variant, but when we have more config options it would be better to be explicit about it.

2022-05-26 14:47 UTC, danielpcox commented on scripts/cibuild
> +  cases=('default' 'with_spire' 'tear_down')
Let's wait on that?

2022-05-26 14:48 UTC, danielpcox commented
I agree. I've got bigger fish to fry at the moment, but I'll swing back around sometime, probably between MVP and 1.0, put my self in a new user's shoes, and try to explain even more stuff.

2022-05-26 15:09 UTC, dontlaugh commented on scripts/cibuild
> +  cases=('default' 'with_spire' 'tear_down')
I defer to @jack-bischoff

2022-05-26 19:47 UTC, jack-bischoff commented
@danielpcox I dug into the cause of the failing spire integration test.

The dashboard proxy (presuming all the other dp proxies too) logs reveal
```
[2022-05-26 19:31:03.683][8][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] StreamSecrets gRPC config stream closed: 3, unable to retrieve all requested identities, missing map[spiffe://greymatter.io/greymatter-mesh.dashboard:true]
```

spire agent logs:
```
time="2022-05-26T19:45:54Z" level=error msg="Error building stream secrets response" error="rpc error: code = InvalidArgument desc = unable to retrieve all requested identities, missing map[spiffe://greymatter.io/greymatter-mesh.redis:true]" method=StreamSecrets pid=6058 service=SDS.v3 subsystem_name=endpoints
```
Not just redis, the logs have errors for the other services too. 


Listing the spire identities:
```
/opt/spire/bin # ./spire-server entry show -socketPath /run/spire/socket/registration.sock
Found 1 entry
Entry ID         : 43e3160c-c36e-4c2a-ac7e-6188580dcfcc
SPIFFE ID        : spiffe://greymatter.io/k8s-workload-registrar/meshes/node/ip-10-1-42-173
Parent ID        : spiffe://greymatter.io/spire/server
Revision         : 0
TTL              : default
Selector         : k8s_psat:agent_node_name:ip-10-1-42-173
Selector         : k8s_psat:cluster:meshes
```

There is only indeed one identity created.

2022-05-26 19:53 UTC, danielpcox commented
Can I have the rest of the agent logs?

2022-05-27 19:20 UTC, dontlaugh requested changes
cue fmt the brand new file(s)

2022-05-27 19:20 UTC, dontlaugh commented on pkg/cuemodule/k8s/outputs/openshift.cue
> +// These are openshift specific configurations
Aren't the above configs openshift-specific, too? Sweep through the comments in this file.

2022-05-27 19:20 UTC, dontlaugh commented on pkg/cuemodule/k8s/outputs/openshift.cue
> +// K8s manifests necessary for spire and openshift
`cue fmt` this file. Since this is a new file, we have an opportunity to run `cue fmt` without major disruption. Other files should be fmted in a separate PR before long.

2022-05-27 19:20 UTC, dontlaugh commented on pkg/cuemodule/k8s/outputs/spire.cue
> +      "registrar.conf": #"""
Nice one :+1:

2022-05-27 19:42 UTC, dontlaugh reviewed
Let's have a CHANGELOG entry for this

2022-05-27 21:48 UTC, dontlaugh approved these changes
I am still setting up a local cluster for this. I'll open issues if I find any.

2022-05-27 21:48 UTC, merged