add redis config
greymatter-io/operator pull request #13
Opened 2021-09-22 14:59 UTC by moosecanswim

2021-09-22 15:21 UTC, moosecanswim commented
[CH 6706]

2021-09-22 17:48 UTC, bcmendoza requested changes

2021-09-22 17:48 UTC, bcmendoza commented on api/v1alpha1/operatorconfig_types.go
> +	SecretName string `json:"certificateSecretName"`
Can you move this into the `store` package and export it?

2021-09-22 17:48 UTC, bcmendoza commented on main.go
> +	var redisUrl string
We don't need command line args for each option -- just the ones the controller-runtime manager requires, plus a `development` flag for convenience in local development. You can remove lines 56-57 and 65-66.

2021-09-22 17:48 UTC, bcmendoza commented on main.go
> +
Let's save this initialization logic for when we call `store.New()`. Maybe move this into `store.go` in a separate function for now?

2021-09-23 16:01 UTC, moosecanswim commented on main.go
> +
done.  also added testing.

2021-09-29 17:50 UTC, closed without merging