Add optional Bugsnag error reporting using go build flags
greymatter-io/operator pull request #147
Opened 2022-08-12 14:26 UTC by jack-bischoff

Bugsnag at best, is irrelevant to end users, and at worst,
may introduce additional attack vectors, get flagged in
software scans, have network traffic blocked entirely, or
just generlly cause pause for customers. To combat these
issues, we need to create separate dev/prod builds.
The dev build will contain the library so we can collect
error metrics during operation in test environments.
The production release will not only disable bugsnag
but will not even contain bugsnag code at all, so that
potential supply chain scans won't flag it.

The solution lies in go build flags and an error
reporter "interface" abstraction. Operator code interacts
with bugsnag library functions through the reporter
package functions. These functions essentially
shadow the bugnsag functions of the same name.
However, this allows us to conditionally compile
empty function stubs instead of the normal
definitions during non-dev builds. Go includes the
empty function stubs if it does not detect a build tag
and includes the working functions if it detects the
"dev" build tag. We pass in this tag through Docker
args.

Lastly, to support this new build pathway, the ci/cd
process expanded and changed to build both images,
push both images to quay, and run the dev image
during integration testing.

Other things to note: I included the CA certs for bugsnag's cert into the operator image as the base ubuntu image doesnt ship with any. I also corrected the pipeline agents to the 22.04. I modified the README to include instructions on how to use the dev version

To test:
First, install the operator without bugsnag (the non-dev latest version). Check the logs to ensure that `Initializing bugsnag` doesn't appear.

Then, follow the instructions in the readme to install the dev version of the operator.  Ensure that the logs contain `Initializing bugsnag`

2022-08-12 17:09 UTC, dontlaugh commented
@alecholmez Ask your boy how to write commit messages.

2022-08-12 17:18 UTC, dontlaugh requested changes
This distinction is indeed required, but a "debug build" is a more accurate name, in my opinion.

Can we fold this into our existing debug build?

2022-08-12 17:18 UTC, dontlaugh commented on main.go
> -	defer func() {
We do not need to catch panics in this codebase, so I support removing this. Better to crash, since operators will be running on k8s anyways.

2022-08-12 17:18 UTC, dontlaugh commented on pkg/reporter/empty_reporter.go
> +
If the `reporter` package is a bugsnag-specific interface, let's give it a bugsnag-specific name.

2022-08-12 18:19 UTC, alecholmez requested changes

2022-08-12 18:19 UTC, alecholmez commented on pkg/reporter/reporter.go
> +func Init() {
A Doc string on the `Init()` function about the bugsnag functionality would be nice.

2022-08-12 18:19 UTC, alecholmez commented on pkg/reporter/reporter.go
> +func Notify(err error, rawData ...interface{}) error {
Docstring here too since it's exported

2022-08-15 20:20 UTC, dontlaugh reviewed
Squash again when this is ready

2022-08-16 18:06 UTC, alecholmez requested changes

2022-08-16 18:06 UTC, alecholmez commented on pkg/bugsnag/reporter.go
> +func Notify(err error, rawData ...interface{}) error {
Just for safekeeping we should probably instrument this through the operator code. No action here but worth a ticket in the future.

2022-08-16 18:21 UTC, dontlaugh commented
What else should we be looking for here? Can you email the team with some links to dashboards, reports, etc.? Have you tested with a pre-release build to see if you've integrated bugsnag successfully?

2022-08-17 15:35 UTC, jack-bischoff commented
> What else should we be looking for here? Can you email the team with some links to dashboards, reports, etc.? Have you tested with a pre-release build to see if you've integrated bugsnag successfully?

@dontlaugh 

Yep, I'll email the team. The free bugsnag plan only allows for 1 account. I put the account information in vault, anyone can log in until we decided if/when to upgrade. I have tested it and bugsnag does report home. It only keeps logs for 7 days on the free plan so I manually triggered some errors today so they appear. Additionally, you can log into jack.k8s.local to verify that the debug-latest build works.

2022-08-18 15:03 UTC, alecholmez submitted a review, later dismissed

2022-08-19 15:00 UTC, dontlaugh commented on .buildkite/pipeline.yaml
> +    if: "build.branch == 'main' || build.tag != null"
nice

2022-08-19 15:03 UTC, dontlaugh requested changes
Cleanup request in `install_operator` function.

2022-08-19 15:03 UTC, dontlaugh commented on scripts/test
> +
We usually use subshells for all `cd`; We can try your way, but clean up the comments around this function, and break the `cue eval` onto a couple of lines.

2022-08-19 20:17 UTC, alecholmez approved these changes
Once the builds are green this is good from my end

2022-08-24 00:45 UTC, dontlaugh requested changes
Looks good, but we need a CHANGELOG update for this.

2022-08-24 00:45 UTC, dontlaugh commented on Dockerfile.debug
> +COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
Nice touch. But I'm a bit worried about the crazy looking URLs in the previous build going stale. Not sure if there's anything better to do about it right now.

We might consider maintaining a "base" image for these debug builds, if there's going to be common assets like this. Are those certs specific to this project, or can they be shared across our projects? 

cc @johnworthing @clbx @mikeschear @joshuaswickirl @moosecanswim

2022-08-24 14:51 UTC, dontlaugh approved these changes
Approved. There are integration test failures, though, and that's a bummer. But it seems to be flaky tests. I'll look into it soon.

2022-08-24 14:54 UTC, merged