WIP Sidecar injection reconciliation
greymatter-io/operator pull request #151
Opened 2022-08-17 21:33 UTC by danielpcox

[sc-7295]

Started in on reconciliation manually, but then realized (thanks to @moosecanswim) that the K8s controller runtime already has the concept and a built-in event loop which solves some of my problems (in particular, deletes).

2022-08-30 13:18 UTC, joel-epstein reviewed
I am currently reviewing the test plan and preparing an environment to test this functionality.

2022-08-30 17:06 UTC, alecholmez requested changes
Mostly this looks great and it's really snappy for me now.

Just a few general notes:
- exported functions and structs should have doc strings (so editors can use them when you look up the doc for the function)
- Can we make use of the interface wrapper types more so we don't have to duplicate a lot of the deployment vs statefulset logic?
- What happens when we need to support a new object?

2022-08-30 18:27 UTC, danielpcox commented on pkg/gmapi/cli.go
> +	c.EnsureClient("MaybeConfigureSidecar")
I think in this case it makes sense to keep it a string literal, since the purpose is logging. It's to say which function is calling EnsureClient. The value isn't otherwise meaningful.

2022-08-30 18:29 UTC, danielpcox commented on pkg/k8sapi/workload_wrappers.go
> +type DeploymentOrStatefulSet interface {
I think "Workload" would be better, since that's the generic name (as far as I know) for "thing that can end up producing pods", which is the level of abstraction at which this interface is defined. I'll switch to that.

2022-08-30 18:31 UTC, danielpcox commented on pkg/mesh_install/installer.go
> +		sort.Strings(sidecarList)
Sorts are cheap, and the lists are very small as far as the computer is concerned. The reason there needs to be two sorts is because if they're the same they need to be in the same order, but you can't be certain you didn't just reload an unsorted list from a GitOps update.

2022-08-30 18:34 UTC, danielpcox commented on pkg/reconciliation/core.go
> +type WorkloadReconciler struct {
Ah yeah. This is a vestige of my learning process. I'll reduce it.

2022-08-30 18:41 UTC, danielpcox commented on pkg/k8sapi/workload_wrappers.go
> +type DeploymentOrStatefulSet interface {
"AbstractWorkload"

2022-08-30 19:00 UTC, danielpcox commented on pkg/reconciliation/core.go
> +	err := r.Get(ctx, req.NamespacedName, deployment)
As per our in-person conversation, I'm going to punt on this for now. The answer may very well be no, because K8s requires me to look things up as concrete types, but I need to work with them as a collection of types. A giant switch statement might work, but we'll revisit this later.

2022-08-30 19:01 UTC, danielpcox commented on pkg/reconciliation/core.go
> +	}
I dealt with this when I removed the outer wrapper class. ✅

2022-08-30 19:02 UTC, danielpcox commented on pkg/reconciliation/core.go
> +func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
Done

2022-08-30 19:03 UTC, danielpcox commented on pkg/gmapi/cli.go
> +	configObjects, kinds, err := operatorCUE.UnifyAndExtractSidecarConfig(name, 8080) // (port unused)
I'll change the comment a bit

2022-08-30 21:06 UTC, danielpcox commented
Squashed

2022-08-30 22:01 UTC, danielpcox commented on pkg/k8sapi/workload_wrappers.go
> +///////////////////////////////////////
K

2022-08-30 22:03 UTC, danielpcox commented on pkg/mesh_install/install.go
> +	i.TriggerInjectedSidecarReconciliation()
Done. I also made it private.

2022-08-30 22:07 UTC, danielpcox commented on pkg/mesh_install/install.go
> +			goto BumpStatefulSets
I don't think so, for the same reason we couldn't do it in `getDeploymentOrStatefulSet`: I need to request them with concrete types from K8s, but I'd need to interact with them generically. The `goto`s are an optimization here, just to avoid skipping a StatefulSet if a Deployment failed.

2022-08-30 22:12 UTC, danielpcox commented on pkg/mesh_install/install.go
> +			goto BumpStatefulSets
As-described, I don't think that would actually work in this case, for the same reason it fails in `getDeploymentorStatefulSet`, and an extra twist. First, I need to look up _all_ Deployments and StatefulSets, so I can't get around having separate DeploymentList and StatefulSetList structs, unless I made a whole other wrapper class for those somehow, which doesn't seem worth it for the one-off need. Second, once I've got one, it doesn't buy me anything to put it in the wrapper class.

Are `goto`s frowned upon in Go? They're a lot less evil than the C versions - function-scoped and Go won't let you skip over variable declarations.

2022-08-30 22:17 UTC, danielpcox commented on pkg/mesh_install/installer.go
> +		time.Sleep(30 * time.Second)
I don't see any reason to avoid waiting or increase the duration in the beginning. The mesh isn't even up when the clock first starts ticking, and then if you want your sidecar to be able to reach Redis in fewer than 30 seconds, you're using the wrong tool anyway.

2022-08-30 22:18 UTC, danielpcox commented on pkg/mesh_install/installer.go
> +	logger.Info("Beginning sidecar list reconciliation loop")
Same comment as below, here.

2022-08-30 22:18 UTC, danielpcox commented on pkg/mesh_install/installer.go
> +	logger.Info("Apply loaded mesh to cluster.")
I... think I disagree, but maybe we should have a conversation about it. I'd make all of the _details_ log lines debugs before making this one a debug. For instance, whenever the k8sapi package is used to Apply changes, that seems more debug than this. This kind of thing is reassuring to users, like a progress bar.

2022-08-30 22:19 UTC, danielpcox commented on pkg/mesh_install/installer.go
> +					sidecarSet[clusterName] = struct{}{}
Less nice than having a built-in set type...

2022-08-30 22:22 UTC, danielpcox commented on pkg/mesh_install/installer.go
> +		time.Sleep(30 * time.Second)
Also by the way, the default sidecar list suffices to service the core mesh components. This separate reconciliation loop is for sidecars deployed into watched namespaces.

2022-08-31 14:10 UTC, danielpcox commented on pkg/mesh_install/install.go
> +			goto BumpStatefulSets
Another way I could avoid `goto` is to spawn two separate goroutines for Deployments and StatefulSets so they can't interfere with one another...

2022-08-31 15:01 UTC, danielpcox commented on pkg/mesh_install/install.go
> +			goto BumpStatefulSets
After some thought, separate goroutines seems like the way to go. I'm going to do that now.

2022-08-31 15:10 UTC, danielpcox commented on pkg/mesh_install/install.go
> +			goto BumpStatefulSets
Done. Have a another look?

2022-08-31 15:52 UTC, danielpcox commented on pkg/mesh_install/install.go
> +			goto BumpStatefulSets
I changed my mind and did the thing we discussed here: https://greymatter.slack.com/archives/C07TJSLQ0/p1661959288022409

2022-08-31 17:36 UTC, alecholmez commented on pkg/mesh_install/installer.go
> +	logger.Info("Apply loaded mesh to cluster.")
Okay thats fine by me. 

Also for the log levels we use https://github.com/rs/zerolog throughout our stuff and that has levels. The default log package just really has fatal and print but the kubernetes logger you use here seems to not have many levels.

2022-08-31 17:37 UTC, alecholmez commented on pkg/mesh_install/installer.go
> +		time.Sleep(30 * time.Second)
Okay works for me! Was just curious on that

2022-08-31 17:37 UTC, alecholmez approved these changes

2022-08-31 18:08 UTC, alecholmez approved these changes

2022-08-31 18:33 UTC, merged