Push containers to Artifactory
greymatter-io/operator pull request #158
Opened 2022-08-25 18:04 UTC by dontlaugh

2022-08-25 18:38 UTC, jack-bischoff commented on scripts/cibuild
> +    container-registry-push $jfrog_latest
Do these images exist on the machine? I don't see where the quay tagged images are re-tagged with jfrog domains

2022-08-25 18:39 UTC, dontlaugh commented on scripts/cibuild
> +    container-registry-push $jfrog_latest
good catch.

2022-08-25 21:47 UTC, jack-bischoff requested changes

2022-08-25 21:47 UTC, jack-bischoff commented on scripts/cibuild
> +  container-retag-image $intermediate $jfrog_latest
I think we need one more to tag debug_intermediate to jfrog_debug_latest

2022-08-26 14:35 UTC, jack-bischoff approved these changes

2022-08-26 14:47 UTC, merged