WIP CUE loading unit tests
greymatter-io/operator pull request #167
Opened 2022-09-08 17:22 UTC by danielpcox

[sc-22033]

2022-09-12 18:34 UTC, alecholmez commented on pkg/cuemodule/load_test.go
> +	t.Run("TestExtractedConfigAndDefaults", func(t *testing.T) {
It looks like you're executing quite a few tests inside of TestLoad. Could these be converted to table driven tests?

https://dave.cheney.net/2019/05/07/prefer-table-driven-tests

2022-09-12 19:49 UTC, danielpcox commented on pkg/cuemodule/load_test.go
> +	t.Run("TestExtractedConfigAndDefaults", func(t *testing.T) {
How about we do that later so we can get these tests in? I don't offhand remember right now if we could have used table-driven tests or not for this, but I don't think we're actually _changing_ any inputs in this set of tests, just confirming several different things from the same input.

2022-09-13 14:58 UTC, alecholmez requested changes
Just some minor things but overall tests look great

2022-09-13 14:58 UTC, alecholmez commented on pkg/cuemodule/load.go
> +var unrecognizedKindLabel = "unrecognized"
Can this be a `const`?

2022-09-13 14:58 UTC, alecholmez commented on pkg/cuemodule/load_test.go
> +	t.Run("TestExtractedConfigAndDefaults", func(t *testing.T) {
Okay no worries. I just read through it and I think this is okay.

2022-09-13 14:58 UTC, alecholmez commented on pkg/cuemodule/load_test.go
> +		//t.Fatal(string(redisListener))
Delete this?

2022-09-13 14:58 UTC, alecholmez commented on pkg/cuemodule/load_test.go
> +		redisListener, err := tempOperatorCUE.ExtractRedisListener() // FUT 2
Not sure what this means:
```
// FUT 2
```

2022-09-13 14:58 UTC, alecholmez commented on pkg/cuemodule/load_test.go
> +		if err != nil {
Wherever you're checking for `if err != nil` lets use assert instead:
```go
assert.NoError(t, err)
```

2022-09-13 14:58 UTC, alecholmez commented on pkg/cuemodule/load_test.go
> +			expectedSubject := helperSpireSubject(
It's generally idiomatic go to do this format instead:
```go
			assert.Equal(
				t,
				helperSpireSubject(
				    defaults.Spire.TrustDomain,
				    config.OperatorNamespace,
				    mesh.Name,
				    clusterName,
                ),
				subjects[i].String(),
            )
```

2022-09-13 14:58 UTC, alecholmez commented on pkg/cuemodule/load_test.go
> +			expectedSubject := helperSpireSubject(
If you'd like to keep the separate variable that also works too but the real nitpick I have is this `)` on the final line of the function call needs its own separate line

2022-09-13 14:58 UTC, alecholmez commented on pkg/cuemodule/load_test.go
> +		if !xdsClusterExists {
This can also be an assert

2022-09-13 14:58 UTC, alecholmez commented on pkg/cuemodule/load_test.go
> +		if !sidecarPortExists {
Assert?

2022-09-13 15:04 UTC, danielpcox commented on pkg/cuemodule/load_test.go
> +		redisListener, err := tempOperatorCUE.ExtractRedisListener() // FUT 2
Function Under Test

2022-09-13 19:37 UTC, alecholmez approved these changes
Looks good!

2022-09-13 22:36 UTC, danielpcox commented
Oh hey, nice job @joel-epstein! Please do the honors.

2022-09-13 22:41 UTC, merged