WIP: Redis system values config
greymatter-io/operator pull request #19
Opened 2021-09-28 14:30 UTC by moosecanswim

2021-09-28 15:40 UTC, bcmendoza requested changes
Good work so far. Requested some changes. When you write tests, you should read in defaults from `fixture.yaml` for `installValues.Redis`, and when you check for the end result after applying the `Redis` option, `installValues.Redis` should be set to `nil`.

2021-09-28 15:40 UTC, bcmendoza commented on api/v1alpha1/installvalues.go
> +func Redis(rc RedisConfig, msh Mesh) func(*InstallValues) {
Looks like you only need the `namespace` string as a parameter vs the entire Mesh object.

2021-09-28 15:40 UTC, bcmendoza commented on api/v1alpha1/installvalues.go
> +		redis_host := ""
Use camelCase variables in Go

2021-09-28 15:40 UTC, bcmendoza commented on api/v1alpha1/installvalues.go
> +				Args([]string{"--appendonly", "yes", "--requirepass", "$(REDIS_PASSWORD)", "--dir", "/data"}),
Add options for `username` and `password` to the `RedisConfig` so that you can pass them in here.

2021-09-28 15:40 UTC, bcmendoza commented on api/v1alpha1/installvalues.go
> +			redis_port_int, _ := strconv.Atoi(redis_port)
Unsafe; but also, since you already know it will be 6379, might as well define it i.e. `redisPortInt := int32(6379)`.

2021-09-28 15:40 UTC, bcmendoza commented on api/v1alpha1/installvalues.go
> +					Name:          svc_name,
`Name` should not be set here, as it will later on be assigned the first argument in the `Port` option (i.e. `"internal-greymatter-redis"`).

2021-09-28 15:40 UTC, bcmendoza commented on api/v1alpha1/installvalues.go
> +				panic(err)
We'll probably need to do validation for the `RedisConfig` prior to passing it to the `Redis` option. Can you just add a TODO here to handle this elsewhere and eventually log it here?

2021-09-28 15:40 UTC, bcmendoza commented on api/v1alpha1/installvalues.go
> +			redis_password = "redis"
?

2021-09-28 15:40 UTC, bcmendoza commented on api/v1alpha1/mesh_types.go
> +	Foo         string       `json:"foo,omitempty"`
Can you remove `Foo` here and then run `make generate manifests`?

2021-09-28 15:40 UTC, bcmendoza commented on api/v1alpha1/installvalues.go
> +		//Initialize default redis values to be reasigned based on redis config
The defaults should already be set in `installValues` (via our embedded YAML files). If `RedisConfig` is not nil, make `installValues.Redis` nil so that `gmcore.Installer` will know not to create an internal Redis deployment.

2021-09-28 15:40 UTC, bcmendoza commented on api/v1alpha1/installvalues.go
> +				"GM_CONTROL_API_REDIS_PORT": string(redis_port),
`redis_port` is already a string

2021-09-29 14:09 UTC, moosecanswim commented on api/v1alpha1/installvalues.go
> +			redis_port_int, _ := strconv.Atoi(redis_port)
wait what i said was dumb https://www.google.com/search?client=firefox-b-1-d&q=int32+max+value

2021-09-29 15:02 UTC, moosecanswim commented on api/v1alpha1/installvalues.go
> +					Name:          svc_name,
Ah gotcha.

2021-09-29 15:13 UTC, moosecanswim commented on api/v1alpha1/installvalues.go
> +			redis_password = "redis"
The `url.Parse()` function return `u.Host` which includes host and port https://gobyexample.com/url-parsing

2021-09-29 16:03 UTC, bcmendoza commented on api/v1alpha1/installvalues.go
> +			redis_password = "redis"
ah, this comment was meant to be about assigning `redis` as the `redis_password`

2021-09-29 16:05 UTC, bcmendoza commented on api/v1alpha1/installvalues.go
> +				Args([]string{"--appendonly", "yes", "--requirepass", "$(REDIS_PASSWORD)", "--dir", "/data"}),
Actually just kidding. These are for the internal deployment, so it should be fine to just generate and use a password here.

2021-09-29 16:06 UTC, bcmendoza commented on api/v1alpha1/mesh_types.go
> +	Password   string `json:"password"`
@moosecanswim Sorry about my earlier comment about adding the `username` and `password` here. These should be added directly to the `url` as a properly formatted Redis connection string.

2021-09-29 16:06 UTC, bcmendoza commented on api/v1alpha1/mesh_types.go
> +	Password   string `json:"password"`
(meaning they can be removed from RedisConfig)

2021-09-29 21:35 UTC, bcmendoza approved these changes
LGTM

2021-09-29 21:42 UTC, merged