address vulnerabilities CVE-2022-27664 and CVE-2022-32149
greymatter-io/operator pull request #197
Opened 2022-11-07 19:52 UTC by moosecanswim

[sc-30371]

Addresses CVEs by pinning `golang.org/x/net` and `golang.org/x/text` indirect dependencies to versions that have the fix.  While in here i also golang.org/x/crypto  version to `0.1.0` to address CVE-2022-30636.

2022-11-07 22:18 UTC, joshuaswickirl requested changes

2022-11-07 22:18 UTC, joshuaswickirl commented on go.mod
> +replace (
Is there a reason to have this second block as opposed to using the one on ln24?

2022-11-07 22:18 UTC, joshuaswickirl commented on go.mod
> +	golang.org/x/text => golang.org/x/text v0.3.8
x/text v0.4.0 is a dep of x/net. We don't need to declare text here again.

2022-11-08 20:33 UTC, clbx approved these changes
lgtm

2022-11-08 20:34 UTC, merged