Ordered k8s apply
greymatter-io/operator pull request #258
Opened 2023-03-28 21:11 UTC by moosecanswim

OPS-58

2023-03-28 21:37 UTC, danielpcox approved these changes
Heck yes

2023-03-28 21:40 UTC, merged

2023-03-28 21:40 UTC, alecholmez requested changes

2023-03-28 21:40 UTC, alecholmez commented on pkg/mesh_install/install.go
> +var InstallOrder KindSortOrder = []string{
You've created a type mask so you don't need to redeclare in the literal syntax
```suggestion
var InstallOrder = KindSortOrder{
```

2023-03-28 21:40 UTC, alecholmez commented on pkg/mesh_install/install.go
> +type KindSortOrder []string
Doc string?

2023-03-28 21:40 UTC, alecholmez commented on pkg/mesh_install/install.go
> +var InstallOrder KindSortOrder = []string{
Also Doc string since it's exported

2023-03-28 21:40 UTC, alecholmez commented on CHANGELOG.md
> +### Changed
Should this be an add? The comment notes an `Added` feature. I'd reword to match the semantics of the changelog header

2023-03-28 21:40 UTC, alecholmez commented on pkg/mesh_install/install.go
> +		return lessByKind(manifests[i], manifests[j], manifests[i].GetObjectKind().GroupVersionKind().Kind, manifests[j].GetObjectKind().GroupVersionKind().Kind, ordering)
This line is super long, we can break it a tiny bit?

2023-03-28 21:40 UTC, alecholmez commented on pkg/mesh_install/install.go
> +func lessByKind(a interface{}, b interface{}, kindA string, kindB string, o KindSortOrder) bool {
Top level scoped variables and parameters should generally be the most descriptive in Go. Short variable names are intended for tightly scoped blocks, like `err` or `i` in a tiny for loop.
```suggestion
func lessByKind(a interface{}, b interface{}, kindA string, kindB string, order KindSortOrder) bool {
```

2023-03-28 21:40 UTC, alecholmez commented on pkg/mesh_install/install.go
> +func lessByKind(a interface{}, b interface{}, kindA string, kindB string, o KindSortOrder) bool {
Also do `a` and `b` need to be `interface{}`? Can they be `client.Object` since that's what gets passed in from the wrapper sort function?

2023-03-28 21:43 UTC, moosecanswim commented on CHANGELOG.md
> +### Changed
Not really a feature for users.  It modifies how k8s stuff are applied.

2023-03-28 21:46 UTC, alecholmez commented on CHANGELOG.md
> +### Changed
I'm looking for something like:
```
- Changed the k8s manifest installation process to specify an order of priority given the resource kind
```

2023-03-28 22:29 UTC, alecholmez commented
Also FWIW I think we need to drop the helm license in this source code too. This is their implementation so we should cover our bases legally. Maybe it's worth breaking this out into a separate file so we can drop the helm license at the top of the file? It's apache 2 which is good just need to make sure we give credit.

2023-03-29 00:15 UTC, moosecanswim commented on CHANGELOG.md
> +### Changed
Updated comment and moved into fixed section.

2023-03-29 00:15 UTC, moosecanswim commented on pkg/mesh_install/install.go
> +		return lessByKind(manifests[i], manifests[j], manifests[i].GetObjectKind().GroupVersionKind().Kind, manifests[j].GetObjectKind().GroupVersionKind().Kind, ordering)
broke it up into more lines

2023-03-29 00:16 UTC, moosecanswim commented on pkg/mesh_install/install.go
> +func lessByKind(a interface{}, b interface{}, kindA string, kindB string, o KindSortOrder) bool {
didnte even need that.  just used the string kind cause thats all we were using

2023-03-29 14:25 UTC, moosecanswim commented
Looking at this it looks like we just need a notice file that sites helm and states that we derived code from what they have.  https://www.apache.org/licenses/LICENSE-2.0.html#redistribution

2023-03-29 14:28 UTC, alecholmez commented
> Looking at this it looks like we just need a notice file that sites helm and states that we derived code from what they have. https://www.apache.org/licenses/LICENSE-2.0.html#redistribution

Beautiful, that works for me. As long as we give credit here I'm good with that