Support vanilla k8s and deploy to kOps
greymatter-io/operator pull request #30
Opened 2021-10-21 15:54 UTC by alecholmez

Signed-off-by: Alec Holmes <alecholmez@me.com> and Brian Mendoza.

This PR adds support for deploying to Kubernetes. The operator has been deployed to a kOps cluster at `gm-operator-dev.k8s.local`, with mesh components installed in the `default` namespace. Note that ingress currently does not work since that is being addressed in a separate PR. For now, you can port-forward to edge at 10808.

To support deploying in Kubernetes without OpenShift/OLM support, this PR:
- Adds scripts that use cfssl to generate a CA and cert/key pair for the operator webhooks
- Cleans up some unused kustomize files that we don't plan to use, i.e. cert-manager
- Makes a few tweaks to get things working in kOps, i..e `securityContext` added to Redis with `fsGroup: 2000`

The README has been updated and is a good guide to follow for testing this PR.

2021-11-01 14:44 UTC, bcmendoza commented on pkg/version/cue.mod/outputs.cue
> +              fsGroup: 2000
Good call. We’ll need to get your PR in first then

2021-11-01 15:37 UTC, moosecanswim commented on pkg/version/cue.mod/outputs.cue
> +              fsGroup: 2000
kk

2021-11-01 17:08 UTC, dontlaugh commented on main.go
> +		LeaderElectionID:        "715805a0.greymatter.io",
Should we leave the TODO in

2021-11-01 17:11 UTC, dontlaugh reviewed
Looks good. I still need to test.

2021-11-01 17:11 UTC, dontlaugh commented on pkg/webhooks/certs.go
> +// NOTE: This code does not run, but is retained here for reference and to use later for generating certs.
Does "does not run" mean "is currently unused"?

2021-11-01 17:22 UTC, bcmendoza commented on pkg/webhooks/certs.go
> +// NOTE: This code does not run, but is retained here for reference and to use later for generating certs.
Yes, it is currently unused. I didn't wanna get rid of this code right away since we may have some use for it later on.

2021-11-01 17:24 UTC, bcmendoza commented on main.go
> +		LeaderElectionID:        "715805a0.greymatter.io",
Yes... I'm not quite sure why kubebuilder has this hard-coded in just yet, or if we even need leader election since there should only ever be one pod that handles requests.

2021-11-01 17:25 UTC, dontlaugh commented on main.go
> +		LeaderElectionID:        "715805a0.greymatter.io",
Not a blocker for this PR

2021-11-01 17:36 UTC, bcmendoza commented
To test with an existing kOps cluster:
1. Ensure you have `NEXUS_USER` and `NEXUS_PASSWORD` sourced in your environment with Docker credentials for pulling Grey Matter images.
2. Run `./scripts/dev deploy k8s` to create all resources used to run the operator, as well as the operator itself
3. You may need to wait a few seconds after the operator is deployed for its server to be launched
4. Run `./scripts/dev sample k8s` to create a Mesh custom resource in the `default` namespace.
5. Watch the log outputs for installing mesh components/dependencies and configuring the mesh
6. To clean up, run `./scripts/dev cleanup k8s`.

2021-11-01 17:57 UTC, dontlaugh commented on scripts/dev
> +  read -p "Build and push a new Docker image? " -n 1 -r
Add (y/n) to this prompt

2021-11-01 18:19 UTC, bcmendoza commented
@dontlaugh This project bundles CLI 3.0 for now and expects it. Later when we move to 4.0, we'll bundle that and support it. I'd rather just `t.Skip` here in the meantime, since the operator should only be running in-cluster, and with the right CLI bundled.

2021-11-01 20:02 UTC, dontlaugh requested changes
Make scripts/bootstrap complain if `kustomize` is missing

2021-11-01 20:36 UTC, dontlaugh commented
After the kustomize thing, this is mergable

2021-11-02 17:08 UTC, dontlaugh approved these changes

2021-11-02 17:12 UTC, merged