Add instructions for generating manifests
greymatter-io/operator pull request #37
Opened 2021-11-09 17:57 UTC by bcmendoza

2021-11-09 18:00 UTC, dontlaugh requested changes
Please start wrapping your markdown at ~80-100 chars

2021-11-12 21:08 UTC, dontlaugh commented on README.md
> +When applying these manifests to your Kubernetes cluster, you'll also need to create a [docker-registry secret](https://kubernetes.io/docs/concepts/configuration/secret/#docker-config-secrets) so the
Wrap the markdown. Something like this 

```suggestion
When applying these manifests to your Kubernetes cluster, you'll also need to create a 
[docker-registry secret](https://kubernetes.io/docs/concepts/configuration/secret/#docker-config-secrets) 
so the Kubelet has access to pull Grey Matter images. Provided that you have the 
necessary Docker username and password, these can be created with the following command:
```

2021-11-12 21:22 UTC, dontlaugh commented on config/default/kustomization.yaml
> +# Adds namespace to all resources, overriding the 'system' namespace.
Right now the manifest we yield is not that big:

```
% ./bin/kustomize build config/k8s | wc -l      
604
```
What are the chances we can move this into a native Go template? Does kustomize do anything else special for us?

2021-11-12 21:29 UTC, dontlaugh commented on pkg/webhooks/webhooks.go
> +			Namespace: "gm-operator",
Any chance we'll need to make this configurable?

2021-11-12 21:32 UTC, dontlaugh commented on pkg/webhooks/webhooks.go
> +	return wl, err
Use a narrower scope for the error
```suggestion
	if !wl.disableCertGen {
		if err := wl.loadCerts(); err != nil {
		    return nil, err
		}
	}

	return wl, nil
```

2021-11-12 21:33 UTC, dontlaugh requested changes
Looks good overall. A few changes and questions.

2021-11-12 21:49 UTC, bcmendoza commented on pkg/webhooks/webhooks.go
> +			Namespace: "gm-operator",
I don't think so. The user really shouldn't be messing with these. We may want to be more deterministic by delegating the creation of these resources to the operator itself, which should limit the amount of manifests needed for the initial install.

2021-11-12 21:59 UTC, bcmendoza commented on config/default/kustomization.yaml
> +# Adds namespace to all resources, overriding the 'system' namespace.
We need Kustomize for two reasons:
1. Operator SDK generates files that are only compatible with it. There are template markers throughout our code that have 1:1 mappings to Kustomize values. I don't feel safe quite yet about moving away from the Operator SDK's generators, mainly in terms of its Openshift nuances.
2. In general, Kustomize makes it easier to add custom overlays and patches on existing manifests. I prefer it to needing to re-invent the wheel with Go templates.

Kustomize also is pretty widely adopted, and even has its own command in `kubectl`.

With all that said, I COULD see us eventually move to Cue, but only after we feel comfortable about not relying on the Operator SDK generators.

2021-11-16 20:01 UTC, dontlaugh commented on config/default/manager_webhook_patch.yaml
> +          - key: tls.crt
Can we add a comment here about where these certs come from

2021-11-16 20:04 UTC, dontlaugh commented on config/k8s/manager_image_patch.yaml
> +        image: docker.greymatter.io/internal/gm-operator:latest-kops
Can we use `latest`? It'd be better if we didn't have to use a special build here.

2021-11-16 20:04 UTC, dontlaugh commented on config/k8s/webhook_secret.yaml
> +  tls.crt: ""
Add a comment about how these certs work, where they come from, etc.

2021-11-16 20:31 UTC, dontlaugh requested changes
Let's spend some time making the CFSSL stuff reusable. I think if you can find a good pattern here it'll have a big payoff.

2021-11-16 20:31 UTC, dontlaugh commented on config/manager/bootstrap_config.yaml
>  imagePullSecretName: gm-docker-secret
Add a comment to this file. Not often you see a one-line yaml file.

2021-11-16 20:31 UTC, dontlaugh commented on pkg/bootstrap/bootstrapconfig_types.go
> +func LoadWithManagerOptions(path string, options manager.Options) (BootstrapConfig, manager.Options, error) {
How many places is this function called? This function is a strange abstraction. An alternative to this is using a global, and getting rid of this function altogether. Something like

```go
var defaultBootstrapConfig =  BootstrapConfig{
		ControllerManagerConfigurationSpec: cfg.ControllerManagerConfigurationSpec{
			// Required as an empty config since options.AndFrom below does not check for nil
			LeaderElection: &basecfg.LeaderElectionConfiguration{},
		},
		// Set default config values
		ClusterIngressName: "cluster",
	}
```
And just invoke the rest of the function's logic directly wherever you're calling this.

2021-11-16 20:31 UTC, dontlaugh commented on pkg/webhooks/cfssl.go
> +	os.Setenv("CFSSL_CA_KEY", string(caKey))
Do we _really_ have to set these as env vars? Or can we provide them to the config some other way.

2021-11-16 20:31 UTC, dontlaugh commented on pkg/webhooks/cfssl.go
> +func serveCFSSL() ([]byte, error) {
We really need an object to hold all this configuration, and put methods on it for start/stop.

```go
type CFSSLServer struct {
  logger *L
  ca []byte
  caKey []byte
  listenerAddress string
}
```
The benefit here is that it lets us make this configurable, and also give us flexibility in how we request the CA cert.

Separate a `Start` method from a separate getter method that returns the cert material, if requested.

And write a constructor

2021-11-16 20:31 UTC, dontlaugh commented on pkg/webhooks/cfssl.go
> +type cfsslResp struct {
If this structure models a json response outside of our control, note that here.

2021-11-16 20:31 UTC, dontlaugh commented on pkg/webhooks/webhooks.go
> +		// but can stay here for now since we're just using it to issue our webhook certs.
Here is where we should do something like

```go
svr := NewCFSSLServer(...)
if err := svr.Start(); err != nil {
// ...
}
caBundle := svr.GetCABundle()  // nil could signal error? maybe return err, too
req := csr.CertificateRequest{
		CN:         "admission",
		Hosts:      []string{"gm-webhook-service.gm-operator.svc"},
		KeyRequest: &csr.KeyRequest{A: "rsa", S: 2048},
	}
cert, key, err := svr.RequestCert(&req)
```

I see your comment waving towards a future where we abstract this out. Let's do that now, and hoist the configuration to the call site, rather than hardcoding it internally. Here we still hard code, but it's in a context wehre configuration is accessible.

2021-11-16 20:34 UTC, bcmendoza commented on pkg/webhooks/cfssl.go
> +	os.Setenv("CFSSL_CA_KEY", string(caKey))
The only other option would be to write to files and provide the file paths.

2021-11-16 20:46 UTC, dontlaugh commented on pkg/webhooks/cfssl.go
> +	os.Setenv("CFSSL_CA_KEY", string(caKey))
okie dokie

2021-11-17 18:30 UTC, dontlaugh approved these changes
Looks good

2021-11-17 19:02 UTC, merged