Add a Go package for exporting a urfave/cli command
greymatter-io/operator pull request #39
Opened 2021-11-19 15:32 UTC by bcmendoza

2021-11-19 17:15 UTC, moosecanswim submitted a review, later dismissed
LGTM

2021-11-19 17:28 UTC, dontlaugh requested changes
A few changes, mostly stylistic

2021-11-19 17:28 UTC, dontlaugh commented on config/config.go
> +		conf.DockerImageURL = "docker.greymatter.io/development/gm-operator:0.0.1"
make this image a global, private constant

2021-11-19 17:28 UTC, dontlaugh commented on config/config.go
> +		return kfs, err
should this be `return nil, err`? or a zero-value'd struct literal, if kfs isn't an interface.

2021-11-19 17:28 UTC, dontlaugh commented on config/config.go
> +func mkFileLoader(efs embed.FS, kfs filesys.FileSystem) func(string, fs.DirEntry, error) error {
Let's add a docstring here.

2021-11-19 17:28 UTC, dontlaugh commented on config/config_test.go
> +
Very nice tests :+1:

2021-11-19 22:27 UTC, dontlaugh approved these changes
Looks good. Go ahead and merge this, if it makes creating the corresponding PR in the cli project easier.

2021-11-22 16:17 UTC, dontlaugh approved these changes

2021-11-22 16:19 UTC, merged