Use SPIRE for mTLS
greymatter-io/operator pull request #40
Opened 2021-11-23 17:09 UTC by bcmendoza

2021-11-24 16:12 UTC, dontlaugh commented
Can we squash pre-merge?

2021-11-30 15:41 UTC, dontlaugh commented
PR for perms over in CLI required?

2021-12-01 14:24 UTC, bcmendoza commented
@alecholmez @dontlaugh 

For now, let's test this PR separately from the CLI. We can test it again when pinning the updated commit in the CLI.

Ensure `GREYMATTER_DOCKER_USERNAME` and `GREYMATTER_DOCKER_PASSWORD` has your Nexus credentials and then run:

```
kubectl apply -k config/context/kubernetes

kubectl create secret docker-registry gm-docker-secret \
  --docker-server=docker.greymatter.io \
  --docker-username=$GREYMATTER_DOCKER_USERNAME \
  --docker-password=$GREYMATER_DOCKER_PASSWORD \
  --docker-email=$GREYMATTER_DOCKER_USERNAME \
  -n gm-operator
```

2021-12-02 15:54 UTC, dontlaugh commented
@alecholmez I'm going to tag this issue and bring it into the sprint for Brian, he can work on this after the cli integration and while you test the basic functionality

2021-12-09 03:18 UTC, bcmendoza commented
@alecholmez @dontlaugh This is ready to test. Let me know if you'd like a quick code walkthrough.

2021-12-09 16:30 UTC, bcmendoza commented on pkg/cli/commands.go
> +		},
When a `cmd` is `run()`, it returns `(string, error)`. (the string is either `stdout` or `stderr`) But `greymatter apply` never exits with an error, so we need to parse the result of `stdout` in order to know that the operation worked.

Whenever an operation fails, the operator requeues the request. This needs to happen sometimes since our current data model has object dependencies enforced by Control API. e.g. If a referenced upstream egress cluster does not yet exist, creating the referencing object is requeued on the loop that runs the commands.

Ideally, we wouldn't need to parse the command output, but instead the CLI would exit with an error whenever `greymatter apply` does not succeed. It makes sense to return an error in our case since apply only takes a single object at a time.

2022-01-04 21:47 UTC, dontlaugh commented on hack/egress-demo.yaml
> +      - image: docker.greymatter.io/internal/responder:egress-demo
This is fine for now, but we'll want to move these somewhere else by next week.

2022-01-04 21:47 UTC, dontlaugh commented on hack/egress-demo.yaml
>          name: fibonacci
change name?

2022-01-04 21:49 UTC, dontlaugh commented on main.go
> +		logger.Error(err, "Failed to configure CFSSL server")
We should wrap the error and let the caller log in one place instead of adding multiple logging statements to this function.

2022-01-04 21:50 UTC, dontlaugh commented on main.go
>  		os.Exit(1)
we can log error here.

2022-01-04 21:53 UTC, dontlaugh commented on pkg/cli/cmd.go
> +	modify func([]byte) ([]byte, error)
What was the motivation behind this new callback?

2022-01-04 21:57 UTC, dontlaugh commented on pkg/fabric/cue/api.cue
> +  service_id: *ServiceName | string
Where do `MeshName`, `ServiceName`, and `Zone` come from? Where are they defined?

2022-01-04 21:58 UTC, dontlaugh commented on pkg/fabric/cue/spire.cue
> +ServiceName: string
I see here. Any reason this isn't `#MeshName` and `#ServiceName`?

2022-01-04 22:04 UTC, dontlaugh commented on pkg/k8sapi/k8sapi.go
> +// Each client.Object argument must implement the necessary interfaces for Reader/Writer interfaces implemented by client.Client.
Specify the interfaces by fully-qualified name here.

2022-01-04 22:06 UTC, dontlaugh commented on pkg/k8sapi/k8sapi.go
> +			logger.Error(err, "SetOwnerReference", "Owner", ownerName, kind, client.ObjectKeyFromObject(obj))
improve these error messages

2022-01-04 22:07 UTC, dontlaugh commented on pkg/k8sapi/k8sapi.go
> +			return "get", err
What is the error case here? Does the caller need the "get" string? If so, why?

2022-01-04 22:09 UTC, dontlaugh requested changes
Just a few questions. Overall I'm comfortable merging this after the nitpicking is addressed.

2022-01-04 23:28 UTC, bcmendoza commented on pkg/cli/cmd.go
> +	modify func([]byte) ([]byte, error)
This is needed to modify a fetched mesh config and then send the modified config back to Control API. It is used to update an existing listener with additional subject names: https://github.com/greymatter-io/operator/blob/spire/pkg/cli/commands.go#L44

2022-01-04 23:28 UTC, bcmendoza commented on pkg/k8sapi/k8sapi.go
> +// Each client.Object argument must implement the necessary interfaces for Reader/Writer interfaces implemented by client.Client.
Can you elaborate?

2022-01-04 23:29 UTC, bcmendoza commented on pkg/fabric/cue/spire.cue
> +ServiceName: string
I prefer to use a hash when defining definitions vs values. It's okay that these values show up in a `cue eval` since I'm not reading them in Go code

2022-01-05 01:31 UTC, bcmendoza commented on pkg/k8sapi/k8sapi.go
> +// Each client.Object argument must implement the necessary interfaces for Reader/Writer interfaces implemented by client.Client.
Oh, you mean by full package path

2022-01-05 02:52 UTC, bcmendoza commented on pkg/k8sapi/k8sapi.go
> +			return "get", err
In the context of this function, any error resulting from Client.Get should be returned as an error to the caller, since failing to Get the resource means no patch can be applied to it (whether the object was not found or Get failed due to some other reason). The "get" string and other strings are returned to give the caller context as to where in the sequence of calls the failure occurred.

I defined an `ActionFunc` type that describes how these functions should be written and how they are used by Apply.

2022-01-05 03:21 UTC, dontlaugh approved these changes

2022-01-05 04:01 UTC, merged