WIP: add the ability to specify alt repos/images for core service downloads
greymatter-io/operator pull request #64
Opened 2022-01-20 00:07 UTC by alecholmez

Signed-off-by: Alec Holmes <alecholmez@me.com>

2022-01-24 21:22 UTC, bcmendoza commented on config/base/deployment_config_patch.yaml
> +        - "--leader-elect"
@alecholmez This doesn't need to be specified here since it's already specified in `config/base/deployment/deployment.yaml`. This file is meant to be a patch that just adds the `bootstrap_config.yaml`. Those two args will be merged into the final result.

2022-01-25 13:09 UTC, bcmendoza commented on config/base/deployment_config_patch.yaml
> +        - "--leader-elect"
Ah, I take it back. It seems entire fields get overwritten if defined in a patch. This can just stay here then.

2022-01-31 12:43 UTC, bcmendoza commented on config/base/deployment/deployment.yaml
> -        - --leader-elect
@alecholmez I removed this flag because the operator doesn't actually read it anymore. Leader elect is turned on by default and otherwise can be overridden via the bootstrap config.

2022-01-31 20:44 UTC, bcmendoza requested changes

2022-01-31 22:15 UTC, alecholmez commented on config/base/deployment/deployment.yaml
> -        - --leader-elect
Okay sweet that sounds good

2022-02-01 19:59 UTC, alecholmez commented on config/config.go
> +			SecretsList:                  strings.Split(c.String("pull-secrets"), ","),
Yup totally reasonable. I had a reason why I made it a generic secrets list but I've forgotten so we'll go with `ImagePullSecretsList` :smile:

2022-02-01 20:19 UTC, alecholmez commented on api/v1alpha1/mesh_types.go
> +	PullSecrets map[string][]string `json:"pull_secrets,omitempty"`
I think I'm good with this. Is the reason to make `Images` a full on go struct that the cue interface will be easier to deal with in the inputs file? If that's the case I'm cool with this. The only reason I did a generic `map[string]string` was to handle image strings without worrying about nesting their structure in the yaml. I don't might the explicitness here, just want to make sure that's what we want.

2. Totally okay with renaming the imagePullSecrets. I'm not tied to that at all.

2022-02-01 22:14 UTC, bcmendoza commented on api/v1alpha1/mesh_types.go
> +	PullSecrets map[string][]string `json:"pull_secrets,omitempty"`
@alecholmez Yeah, a Go struct will help for both CUE and for the user applying manifests. We get built in validation from those kubebuilder markers on the CRD.

2022-02-03 19:07 UTC, bcmendoza requested changes

2022-02-03 19:07 UTC, bcmendoza commented on pkg/cuemodule/base/inputs.cue
> +ImagePullSecrets: mesh.spec.image_pull_secrets
This isn't being read anywhere. You'll want to make sure each listed image pull secret is also added to this list: https://github.com/greymatter-io/operator/blob/main/pkg/cuemodule/base/outputs.cue#L54-L56

2022-02-03 20:42 UTC, alecholmez commented on api/v1alpha1/mesh_types.go
> +	Control     string `json:"control,omitempty"`
Oh oops, I chose not to add control-api because I figured we could derive the version from control since they should always match. But i'll add back control-api

2022-02-03 20:42 UTC, alecholmez commented on pkg/cuemodule/base/inputs.cue
> +ImagePullSecrets: mesh.spec.image_pull_secrets
Oh okay cool, i'll fix this

2022-02-04 13:56 UTC, bcmendoza approved these changes
LGTM! Thanks for all your work on this. Can you clean up the commit history and ping me when it's ready?

2022-02-04 16:03 UTC, merged