CUE refactor
greymatter-io/operator pull request #97
Opened 2022-04-05 23:45 UTC by danielpcox

Most of the CUE refactor, though not yet with all of the features restored that I broke during the process (detailed here: https://app.shortcut.com/grey-matter/story/11585/resurrect-skipped-operator-features )

## Changed

- Completely new CUE for both Kubernetes manifests and Grey Matter config, currently still rooted
  under `pkg/cuemodule/new_structure` (and will eventually be moved into the root once the Spire
  support is complete) following a philosophy of readability and malleability.
- Operator Go now loads CUE generically, such that nearly all changes to deployment configuration
  require no changes to the Go.
- Deployment assist is now opt-in, with labels `"greymatter.io/inject-sidecar-to": "<port num>"`
  (default is to omit the label) and `"greymatter.io/configure-sidecar": "<boolean>"` (default
  "false".)
- Operator itself now runs as a StatefulSet rather than a Deployment.
- One-Mesh/One-Operator - Multiple meshes require multiple operators (they do yet not play nicely
  together, but the target for multi-mesh support is to support graceful interop.)
- For now, automatically deploys the default Mesh described in the CUE source shortly after startup.
  Later, this will be an opt-in flag in the CUE itself so users can decide.
- Switch to ECDSA 256 certificates for speed and security.

## To Test

Follow the updated "Quick Install" block of the README.

2022-04-06 21:53 UTC, dontlaugh requested changes
An improvement, overall. I have a few nitpicks but after that I'd be good to merge.

----

For the future, ff you find a way to do the following next, it would be good:

* `panic` in the CUE processing stuff, if I understand correctly, is fine, since evaluating CUE is deterministic, and we can be assured that "it would never happen". But it would be good to find a way to return more errors in there, and log at a higher level.
* The `Cmd` and apply abstractions seem to introduce more async stuff than we need. But I could be wrong.

2022-04-06 21:53 UTC, dontlaugh commented on main.go
> +	operatorCUE, initialMesh := cuemodule.LoadAll(cueRoot) // panics if unsuccessful
Let's not panic. Return three params, and log fatal.

2022-04-06 21:53 UTC, dontlaugh commented on pkg/cli/cli.go
> +	operatorCUE cuemodule.OperatorCUE
```suggestion
	operatorCUE *cuemodule.OperatorCUE
```
This feels like it should be a pointer. Passing a copied value could trip us up.

2022-04-06 21:53 UTC, dontlaugh commented on pkg/cli/cli.go
> +func New(ctx context.Context, operatorCUE cuemodule.OperatorCUE, mTLSEnabled bool) (*CLI, error) {
Cool :+1:

2022-04-06 21:53 UTC, dontlaugh commented on pkg/cli/cli.go
> +	configureSidecar := annotations[wellknown.ANNOTATION_CONFIGURE_SIDECAR]
Whatever's handing us these annotations has an opportunity to be polite:

* scan the greymatter.io/operator prefix (or whatever it is)
* WARN on bad values, e.g. "F4Lse"

2022-04-06 21:53 UTC, dontlaugh commented on pkg/installer/install.go
> +			logger.Info("DEBUG:", "secret", secret)
This is just the secret's name, right? not the value? let's not log the value.

2022-04-06 21:53 UTC, dontlaugh commented on pkg/installer/installer.go
> +	k8sClient client.Client
Let's make this k8sClient a pointer

2022-04-06 21:53 UTC, dontlaugh requested changes
oh, and squash

2022-04-07 15:52 UTC, alecholmez requested changes
Nothing major from me looks great. 

Just maybe one thing, the `logger.Info("DEBUG: ")` statements can become `logger.Debug()` so they are hidden

2022-04-07 15:52 UTC, alecholmez commented on config/context/local-refactored/patches.yaml
> +        image: "docker.greymatter.io/internal/gm-operator:local_refactored"
Do we want this checked in? We might want to make a note to clean this up

2022-04-07 15:52 UTC, alecholmez commented on pkg/cli/cli.go
>  	// Close an existing cmds channel if updating
this comment might be out of date?

2022-04-07 15:52 UTC, alecholmez commented on pkg/cli/cli.go
> +	logger.Info("DEBUG: Attempting to configure sidecar with values", "name", name, "annotations", annotations)
Maybe change this to `logger.Debug`?

2022-04-07 15:52 UTC, alecholmez commented on pkg/cli/cli.go
> +	if injectSidecar {
This block looks like it could be a function, I think you use it above as well?

2022-04-07 15:52 UTC, alecholmez commented on pkg/cli/client.go
> +		// TODO Confirm the one-operator <=> one-mesh concept, then you can delete these comments:
These still valid?

2022-04-07 15:52 UTC, alecholmez commented on pkg/cli/client.go
>  					// Create a NOOP shared_rules object to ensure that we can write to Control.
I'd maybe move this comment above the `if _, err := (Cmd{` it helps with readability

2022-04-07 15:52 UTC, alecholmez commented on pkg/cli/client_test.go
> +//func TestNewClient(t *testing.T) {
Maybe delete if we don't need this? or this is in limbo until spire is done

2022-04-07 15:52 UTC, alecholmez commented on pkg/cuemodule/load.go
> +func LoadAll(cuemoduleRoot string) (OperatorCUE, *v1alpha1.Mesh) {
Nice, maybe add some go doc strings above these functions so they look nice in the `godoc`

2022-04-07 15:52 UTC, alecholmez commented on pkg/installer/install.go
> +			logger.Info("DEBUG:", "secret", secret)
This is probably worthy of at least a `logger.Debug()`, maybe keep it out of the info level if its just the name

2022-04-07 19:21 UTC, danielpcox commented on config/context/local-refactored/patches.yaml
> +        image: "docker.greymatter.io/internal/gm-operator:local_refactored"
For this PR only, yes I want to check it in. I will clean it up later.

2022-04-07 20:22 UTC, dontlaugh commented on main.go
> +	inst, err := installer.New(&c, operatorCUE, initialMesh, cueRoot, gmcli, cfssl, cfg.ClusterIngressName)
jack_nicholson_nodding.gif

2022-04-07 20:30 UTC, danielpcox commented on pkg/cli/cli.go
>  	// Close an existing cmds channel if updating
I don't think so. I just changed it from dealing with potentially many meshes to just one, but the context still needs cancelling for that one mesh.

2022-04-07 21:58 UTC, dontlaugh commented on pkg/cli/cli.go
> +	if injectSidecar {
for now, let's leave this alone unless Daniel wants to change it

2022-04-07 22:01 UTC, dontlaugh reviewed
Squash this down, force push, and I'll approve

2022-04-11 18:38 UTC, dontlaugh submitted a review, later dismissed

2022-04-11 18:38 UTC, dontlaugh commented
oh I didn't see the failing build. let's try to get that green, even if it takes some time here.

2022-04-11 20:21 UTC, merged